name = "worker-article-checker"
main = "src/worker.js"
compatibility_date = "2024-05-29"
workers_dev = true

kv_namespaces = [
  { binding = "checkerPrompts", id = "" }
]

[vars]
OPENAI_API_KEY = ""
BRAVE_API_KEY = ""
LLM_ENDPOINT = ""
LLM_MODEL = "gpt-4o"
SEARCH_ENDPOINT = ""
TOKEN_GITHUB = ""