name: Article Check Comment

on:
  issue_comment:
    types: [created]

jobs:
  interact-with-cloudflare-worker:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/articlecheck')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call Cloudflare Worker
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          ACTION: ${{ github.event.action }}
          PR_URL: ${{ github.event.issue.pull_request.url }}
          PR_HTML_URL: ${{ github.event.issue.pull_request.html_url }}
          PR_DIFF_URL: ${{ github.event.issue.pull_request.diff_url }}
          PR_PATCH_URL: ${{ github.event.issue.pull_request.patch_url }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          curl -X POST "$WORKER_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "action": "'"${ACTION}"'",
            "issue": {
              "pull_request": {
                "url": "'"${PR_URL}"'",
                "html_url": "'"${PR_HTML_URL}"'",
                "diff_url": "'"${PR_DIFF_URL}"'",
                "patch_url": "'"${PR_PATCH_URL}"'",
                "merged_at": null
              }
            },
            "comment": {
              "body": "'"${COMMENT_BODY}"'"
            }
          }'
